### ISSUE TITLE
How to setup this project

### ISSUE THREAD

**Issue by sakshamnegi12** [UmarSheikh122/ChromeExtensionCookie#1]
Brother Can you tell me How to setup this project and How to use ?

**Comment by iumarsh** [comment]
This is only the backend of a chrome extension, what’s your usecase?

**Comment by sakshamnegi12** [comment]
I am looking for a chrome extension that can export cookies to server and same we can import to other browser

**Comment by iumarsh** [comment]
Yes,  it serves the exact same purpose. It’s a simple backend you can run
this and you can check the frontend of it as well.

**Comment by sakshamnegi12** [comment]
Yeah I have tried to setup but How to get into the Backend what about the admin portal. Can we connect over whatsapp  for the same ?

**Comment by iumarsh** [comment]
There’s a frontend repository, I’m a little busy but I can connect with you
on Sunday and can help you setup this.

**Comment by sakshamnegi12** [comment]
Can we connect today ?

**Comment by iumarsh** [comment]
Let’s connect tomorrow or I’ll share the loom video with you like how can
you setup both the frontend and backend.

**Comment by sakshamnegi12** [comment]
hey brother Can we connect please ?

**Comment by iumarsh** [comment]
Can you please drop me a message on whatsapp and we can connect tonight.

+923316408235

**Comment by sakshamnegi12** [comment]
Thanks a lot brother...Your help means a lot..Hats off to you
